#!/usr/bin/env ruby

#^syntax detection

# -*- encoding : utf-8 -*-
site "http://community.opscode.com/api/v1"

cookbook 'apt', 
  git: 'https://github.com/fnichol/chef-apt'
cookbook 'build-essential'
cookbook 'git', 
  git: 'https://github.com/fnichol/chef-git'
cookbook 'rvm', 
  git: 'git://github.com/fnichol/chef-rvm'
cookbook 'mongodb'
cookbook 'nginx'
